---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 陈义.
--- DateTime: 2023/3/3 14:33
---
tab1 = { key1 = "val1", key2 = "val2", "val3" }
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
end

tab1.key1 = nil
for k, v in pairs(tab1) do
    print(k .. " - " .. v)
end